hackery

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,6 +1,7 @@
-# Fail fast and fail hard.
+#!/usr/bin/env bash
+
 set -eo pipefail
-# Prepend proper path for virtualenv hackery. This will be deprecated soon.
+
 export PATH=:/usr/local/bin:$PATH
 
 # Paths.
@@ -9,24 +10,18 @@ ROOT_DIR=$(dirname $BIN_DIR)
 BUILD_DIR=$1
 CACHE_DIR=$2
 
-# The detected application type (`Python`|`Python/Django`).
-NAME=$($BIN_DIR/detect $BUILD_DIR)
+CACHED_DIRS=".heroku"
 
 # Where to store the Pip download cache.
-CACHED_DIRS=".heroku"
+
 PIP_DOWNLOAD_CACHE=${PIP_DOWNLOAD_CACHE:-$CACHE_DIR/pip_downloads}
 
-# Static configurations for virtualenv caches.
-LEGACY_VIRTUALENV_LOC="."
-MODERN_VIRTUALENV_LOC=".heroku/venv"
-LEGACY_VIRTUALENV_DIRS="bin include lib"
-LEGACY_VIRTUALENV_TRIGGER="lib/python2.7"
-PROFILE_PATH="$1/.profile.d/python.sh"
+VIRTUALENV_LOC=".heroku/venv"
+LEGACY_TRIGGER="lib/python2.7"
+PROFILE_PATH="$BUILD_DIR/.profile.d/python.sh"
 
-
-# Python version. This will be used in the future to specify custom Pythons.
-PYTHON_VERSION="2.7.2"
-PYTHON_EXE="python2.7"
+DEFAULT_PYTHON_VERSION="python-2.7.3"
+PYTHON_EXE="/app/.heroku/python/bin/python"
 
 # Sanitizing environment variables.
 unset GIT_DIR PYTHONHOME PYTHONPATH LD_LIBRARY_PATH LIBRARY_PATH
@@ -34,39 +29,23 @@ unset GIT_DIR PYTHONHOME PYTHONPATH LD_LIBRARY_PATH LIBRARY_PATH
 # We'll need to send these statics to other scripts we `source`.
 export PIP_DOWNLOAD_CACHE BUILD_DIR CACHE_DIR BIN_DIR PROFILE_PATH
 
-# Syntax sugar.
-indent() {
-  RE="s/^/       /"
-  [ $(uname) == "Darwin" ] && sed -l "$RE" || sed -u "$RE"
-}
+APP_DIR='/app'
+TMP_APP_DIR=$CACHE_DIR/tmp_app_dir
 
-# Virtualenv wrapper.
-function virtualenv (){
-  python "$ROOT_DIR/vendor/virtualenv-1.7.2/virtualenv.py" "$@"
-}
+mkdir -p $TMP_APP_DIR
+deep-mv $APP_DIR $TMP_APP_DIR
+deep-mv $BUILD_DIR $APP_DIR
 
-# Buildpack Steps.
-function puts-step (){
-  echo "-----> $@"
-}
+ORIG_BUILD_DIR=$BUILD_DIR
+BUILD_DIR=$APP_DIR
 
-# Buildpack Warnings.
-function puts-warn (){
-  echo " !     $@"
-}
+export PATH=$BUILD_DIR/.heroku/python/bin:$PATH
+export PYTHONUNBUFFERED=1
+export LANG=en_US.UTF-8
+export LIBRARY_PATH=/app/.heroku/vendor/lib
+export LD_LIBRARY_PATH=/app/.heroku/vendor/lib
 
-# Usage: $ set-env key value
-function set-env (){
-  echo "export $1=$2" >> $PROFILE_PATH
-}
-
-# Usage: $ set-default-env key value
-function set-default-env (){
-  echo "export $1=\${$1:-$2}" >> $PROFILE_PATH
-}
-
-# ## Build Time
-#
+source $BIN_DIR/utils
 
 # Switch to the repo's context.
 cd $BUILD_DIR
@@ -84,32 +63,18 @@ if [ ! -f requirements.txt ]; then
   echo "-e ." > requirements.txt
 fi
 
+# If no runtime given, assume default version.
+if [ ! -f runtime.txt ]; then
+  puts-step "No runtime.txt provided; assuming $DEFAULT_PYTHON_VERSION."
+  echo $DEFAULT_PYTHON_VERSION > runtime.txt
+fi
+
 # ### The Cache
 mkdir -p $CACHE_DIR
-[ ! "$(ls -A $CACHE_DIR)" ] && export FRESH_APP=1
+
+#[ ! "$(ls -A $CACHE_DIR)" ] && export FRESH_APP=1
 
 
-# Nice defaults.
-LEGACY_VIRTUALENV=false
-VIRTUALENV_LOC=$MODERN_VIRTUALENV_LOC
-
-# Support "old-style" virtualenvs.
-if [ -d $CACHE_DIR/$LEGACY_VIRTUALENV_TRIGGER ]; then
-  LEGACY_VIRTUALENV=true
-  VIRTUALENV_LOC=$LEGACY_VIRTUALENV_LOC
-  CACHED_DIRS=$LEGACY_VIRTUALENV_DIRS
-
-  # Warn for a checked-in virtualenv.
-  if [ -d "lib" ] || [ -d "bin" ]; then
-    puts-warn "You have a virtualenv checked in. You should ignore the appropriate paths in your repo. See http://devcenter.heroku.com/articles/gitignore for more info.";
-  fi
-
-  # Reject a conflicting checked-in virtualenv.
-  if [ -f "lib/python2.7" ]; then
-    puts-warn "Checked-in virtualenv conflict."
-    exit 1;
-  fi
-fi
 
 # Restore old artifacts from the cache.
 for dir in $CACHED_DIRS; do
@@ -120,21 +85,56 @@ set +e
 # Create set-aside `.heroku` folder.
 mkdir .heroku &> /dev/null
 HEROKU_DIR_STATUS=$?
-
-# TODO: This is a new app, disable injection.
-# [ $HEROKU_DIR_STATUS -eq 0 ] && {
-  #TODO: touch .heroku/injection_disabled
-# }
 set -e
 
 # Buildpack profile init script
 mkdir -p $(dirname $PROFILE_PATH)
 
-# ### Virtualenv Setup
-#
+set +e
+PYTHON_VERSION="python-2.7.3"
 
-# Create the virtualenv. Rebuild if corrupt.
-# TODO: Bootstrap a bottled Python VM...
+# Install Python.
+if [ -f .heroku/python-version ]; then
+  if [ ! $(cat .heroku/python-version) = $PYTHON_VERSION ]; then
+    puts-step "Found $(cat .heroku/python-version), removing."
+    rm -fr .heroku/python
+  else
+    SKIP_INSTALL=1
+  fi
+fi
+
+if [ ! "$SKIP_INSTALL" ]; then
+  puts-step "Preparing Python runtime ($PYTHON_VERSION)"
+  curl http://envy-versions.s3.amazonaws.com/$PYTHON_VERSION.tar.bz2 -s | tar jx &> /dev/null
+  if [[ $? != 0 ]] ; then
+    puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
+    puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
+    exit 1
+  fi
+  mv python .heroku/python
+
+  # Record for future reference.
+  echo $PYTHON_VERSION > .heroku/python-version
+  WORKING_DIR=$(pwd)
+
+  # Prepare it for the real world
+  puts-step "Installing Distribute (0.6.34)"
+  cd $ROOT_DIR/vendor/distribute-0.6.34/
+  python setup.py install  &> /dev/null
+  cd $WORKING_DIR
+
+  puts-step "Installing Pip (1.2.1)"
+  cd $ROOT_DIR/vendor/pip-1.2.1/
+  python setup.py install  &> /dev/null
+  cd $WORKING_DIR
+
+  hash -r
+else
+  puts-step "Using Python runtime ($PYTHON_VERSION)"
+fi
+
+set -e
+
 
 set +e
 puts-step "Preparing Python interpreter ($PYTHON_VERSION)"
@@ -171,21 +171,13 @@ if (grep -Fiq "hg+" requirements.txt) then
 fi
 
 # Install ez_setup
-puts-step "Installing ez_setup using pip version $(pip --version | awk '{print $2}')"
-pip install --use-mirrors --exists-action=w --src=./.heroku/src ez_setup | indent
+#puts-step "Installing ez_setup using pip version $(pip --version | awk '{print $2}')"
+#pip install --use-mirrors -r requirements.txt --exists-action=w --src=./.heroku/src | cleanup | indent
 
 # Install dependencies with Pip.
 puts-step "Installing dependencies using pip version $(pip --version | awk '{print $2}')"
 pip install --use-mirrors -r requirements.txt --exists-action=w --src=./.heroku/src | indent
 
-# Do additional application hackery if applications appears to be a Django app.
-# Optionally, disable all Django-specific changes with `DISABLE_INJECTION` env.
-#
-# See [`bin/steps/django`](django.html).
-
-if [ "$NAME" = "Python/Django" ]; then
-  source $BIN_DIR/steps/django/init
-fi
 
 # Make Virtualenv's paths relative for portability.
 set +e
@@ -208,18 +200,17 @@ done
 
 # Set context environment variables.
 
-set-env PATH '$HOME/.heroku/venv/bin:$PATH'
-set-default-env PYTHONUNBUFFERED true
+set-env PATH '$HOME/.heroku/venv/bin:$HOME/.heroku/python/bin:$PATH'
+set-env PYTHONUNBUFFERED true
 set-default-env LIBRARY_PATH /app/.heroku/vendor/lib
 set-default-env LD_LIBRARY_PATH /app/.heroku/vendor/lib
+
 set-default-env LANG en_US.UTF-8
 set-default-env PYTHONHASHSEED random
-set-default-env PYTHONHOME /app/.heroku/venv/
+set-default-env PYTHONHOME /app/.heroku/python
 set-default-env PYTHONPATH /app/
 
 #install OpenCV
-
-# from https://github.com/freeformz/heroku-buildpack-io/blob/master/bin/compile
 
 set -e
 
@@ -302,4 +293,33 @@ tar xzf ${cache_target} -C ${build_target}
 # Experimental post_compile hook.
 source $BIN_DIR/steps/hooks/post_compile
 
-# <a href="http://github.com/heroku/heroku-buildpack-python"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://d3nwyuy0nl342s.cloudfront.net/img/7afbc8b248c68eb468279e8c17986ad46549fb71/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub"></a>
+
+indent() {
+  RE="s/^/       /"
+  [ $(uname) == "Darwin" ] && sed -l "$RE" || sed -u "$RE"
+}
+
+# Virtualenv wrapper.
+function virtualenv (){
+  python "$ROOT_DIR/vendor/virtualenv-1.7.2/virtualenv.py" "$@"
+}
+
+# Buildpack Steps.
+function puts-step (){
+  echo "-----> $@"
+}
+
+# Buildpack Warnings.
+function puts-warn (){
+  echo " !     $@"
+}
+
+# Usage: $ set-env key value
+function set-env (){
+  echo "export $1=$2" >> $PROFILE_PATH
+}
+
+# Usage: $ set-default-env key value
+function set-default-env (){
+  echo "export $1=\${$1:-$2}" >> $PROFILE_PATH
+}
